create table public.waitlist_entries (
    id bigint generated by default as identity primary key,
    email text not null unique,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.waitlist_entries enable row level security;

-- Allow public read access for now (adjust later if needed)
create policy "Allow public read access" on public.waitlist_entries for select using (true);

-- Allow public insert access for simplicity during signup phase.
create policy "Allow public insert access" on public.waitlist_entries for insert with check (true);

-- Add comment for the table
comment on table public.waitlist_entries is 'Stores email addresses collected from the waitlist signup form.';
