-- Create users table (referencing auth.users)
create table users (
  id uuid references auth.users on delete cascade not null primary key,
  email text unique,
  created_at timestamptz default timezone('utc'::text, now()) not null
);

-- Create vendors table
create table vendors (
  id bigint generated by default as identity primary key,
  name text not null,
  created_at timestamptz default timezone('utc'::text, now()) not null
);

-- Create projects table
create table projects (
  id bigint generated by default as identity primary key,
  user_id uuid references public.users on delete cascade not null,
  name text not null,
  created_at timestamptz default timezone('utc'::text, now()) not null
);

-- Create charges table
create table charges (
  id bigint generated by default as identity primary key,
  user_id uuid references public.users on delete cascade not null,
  vendor_id bigint references public.vendors on delete set null, -- Allow vendor deletion without deleting charge
  invoice_id text, -- Unique identifier from the vendor's invoice
  date date not null,
  description text,
  amount decimal(10, 2) not null, -- Assuming precision 10, scale 2
  currency char(3) not null, -- ISO 4217 currency code (e.g., 'USD')
  category text, -- Auto-assigned or manually set category
  created_at timestamptz default timezone('utc'::text, now()) not null,
  unique (user_id, vendor_id, invoice_id) -- Prevent duplicate invoice entries per user/vendor
);

-- Create budgets table
create table budgets (
  id bigint generated by default as identity primary key,
  user_id uuid references public.users on delete cascade not null,
  scope text not null, -- e.g., 'overall', 'project:project_id', 'vendor:vendor_id'
  amount decimal(10, 2) not null,
  created_at timestamptz default timezone('utc'::text, now()) not null
);

-- Create charge_tags (linking charges to projects)
create table charge_tags (
  charge_id bigint references public.charges on delete cascade not null,
  project_id bigint references public.projects on delete cascade not null,
  primary key (charge_id, project_id) -- Composite primary key
);

-- Add indexes for common query patterns
create index charges_user_id_idx on charges (user_id);
create index charges_vendor_id_idx on charges (vendor_id);
create index charges_date_idx on charges (date);
create index projects_user_id_idx on projects (user_id);
create index budgets_user_id_idx on budgets (user_id);
